name: wildfires
channels:
  - conda-forge
  - defaults
dependencies:
  - affine>=2.3.0
  - black>=19.10b0
  - cartopy>=0.18.0
  - cdsapi>=0.2.7
  - cf_units>=2.0.1
  - cloudpickle>=1.3.0
  - dask-jobqueue>=0.7.1
  - dask-ml>=1.2
  - dask-xgboost>=0.1.10
  - dask>=2.14.0
  - dill>=0.3.1.1
  - eli5>=0.10
  - fiona>=1.8.13
  - flake8>=3.7.9
  - gitpython>=3.1.1
  - h5py>=2.10.0
  - hdf4>=4.2.13
  - hdf5>=1.10.5
  - ipdb>=0.12.3
  - ipykernel>=5.2.1
  - ipython>=7.13.0
  - iris>=2.4.0
  - isort>=4.3.21
  - joblib>=0.14.1
  - jupyter_client>=6.1.3
  - jupyter_console>=6.1.0
  - jupyter_core>=4.6.3
  - jupyterlab>=2.1.0
  - jupyterlab_server>=1.1.1
  - matplotlib-base>=3.2.1
  - nb_conda_kernels>=2.2.3
  - nbconvert>=5.6.1
  - nbdime>=2.0.0
  - nbformat>=5.0.6
  - netcdf4>=1.5.3
  - nodejs>=13.13.0
  - numpy>=1.18.1
  - pandas>=1.0.3
  - pdpbox>=0.2.0
  - pip>=20.0.2
  - pre_commit>=2.3.0
  - psutil>=5.7.0
  - pyflakes>=2.1.1
  - pyhdf>=0.10.2
  - pylint>=2.4.4
  - pytables>=3.6.1
  - pytest-cov>=2.8
  - pytest>=5.4
  - python-dateutil>=2.8.1
  - python-graphviz>=0.13.2
  - python>=3.7
  - pyyaml>=5.3.1
  - rasterio>=1.1.3
  - scikit-learn>=0.23.1
  - scipy>=1.4.1
  - shap>=0.35.0
  - statsmodels>=0.11.1
  - tqdm>=4.45.0
  - xgboost>=1.0.2
  - pip:
    - git+https://github.com/akuhnregnier/ALEPython.git@working#egg=alepython
    - git+https://github.com/akuhnregnier/clean_ipynb.git@working#egg=clean_ipynb
    - git+https://github.com/akuhnregnier/era5analysis.git@master#egg=era5analysis
    - git+https://github.com/akuhnregnier/jupyter-notebook-tools.git@master#egg=jupyter-notebook-tools
    - git+https://github.com/christophM/rulefit.git@master#egg=rulefit
    - jupyterlab-code-formatter>=1.2.4
    - logging-tree>=1.8.1
    - neovim-remote>=2.4.0
    - neovim>=0.3.1
    - pynvim>=0.4.1
