channels:
  - conda-forge
  - defaults
dependencies:
  - affine
  - beautifulsoup4
  - black
  - cartopy
  - cdsapi
  - cf_units
  - cloudpickle
  - dask
  - dask-jobqueue
  - dill
  - fiona
  - flake8
  - gitpython
  - h5py
  - hdf4
  - hdf5
  - ipdb
  - ipykernel
  - ipython
  - iris
  - isort
  - joblib
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - matplotlib
  - matplotlib-base
  - nb_conda_kernels
  - nbconvert
  - nbdime
  - nbformat
  - nbstripout
  - netcdf4
  - nodejs
  - numpy
  - pandas
  - pip
  - pre_commit
  - pyflakes
  - pyhdf
  - pylint
  - pytest
  - python
  - python-dateutil
  - python-graphviz
  - pyyaml
  - rasterio
  - requests
  - scikit-learn
  - scipy
  - soupsieve
  - statsmodels
  - tqdm
  - pip:
    - https://github.com/akuhnregnier/clean_ipynb/archive/own-working.zip
    - https://github.com/akuhnregnier/era5analysis/archive/0.1.0.zip
    - https://github.com/akuhnregnier/jupyter-notebook-tools/archive/master.zip
    - jupyterlab-code-formatter
    - logging-tree
    - neovim
    - neovim-remote
    - pynvim
